### ISSUE TITLE
Assertion Error

### ISSUE THREAD

**Issue by DebapriyaHazra** [e-271/few-shot-gan#15]
I am getting this error when I am trying to train the model on my dataset. I have first created the tfrecord files with dataset_tool.py. 

Streaming data using training.dataset.TFRecordDataset...
Traceback (most recent call last):
  File "run_training.py", line 254, in <module>
    main()
  File "run_training.py", line 249, in main
    run(**vars(args))
  File "run_training.py", line 169, in run
    dnnlib.submit_run(**kwargs)
  File "F:\Debapriya\Medical\Bone Marrow\Code\Thesis\few-shot-gan-master\few-shot-gan-master\dnnlib\submission\submit.py", line 343, in submit_run
    return farm.submit(submit_config, host_run_dir)
  File "F:\Debapriya\Medical\Bone Marrow\Code\Thesis\few-shot-gan-master\few-shot-gan-master\dnnlib\submission\internal\local.py", line 22, in submit
    return run_wrapper(submit_config)
  File "F:\Debapriya\Medical\Bone Marrow\Code\Thesis\few-shot-gan-master\few-shot-gan-master\dnnlib\submission\submit.py", line 280, in run_wrapper
    run_func_obj(**submit_config.run_func_kwargs)
  File "F:\Debapriya\Medical\Bone Marrow\Code\Thesis\few-shot-gan-master\few-shot-gan-master\training\training_loop.py", line 151, in training_loop
    training_set = dataset.load_dataset(data_dir=dnnlib.convert_path(train_data_dir), verbose=True, **dataset_args)
  File "F:\Debapriya\Medical\Bone Marrow\Code\Thesis\few-shot-gan-master\few-shot-gan-master\training\dataset.py", line 207, in load_dataset
    dataset = dnnlib.util.get_obj_by_name(class_name)(**kwargs)
  File "F:\Debapriya\Medical\Bone Marrow\Code\Thesis\few-shot-gan-master\few-shot-gan-master\training\dataset.py", line 54, in __init__
    assert os.path.isdir(self.tfrecord_dir)
AssertionError

**Comment by JannikHock30** [comment]
I have the same problem. Has anyone found a solution?
